### ISSUE TITLE
Extension

### ISSUE THREAD

**Issue by Jireck-npds** [npds/modules#1]
incomprehensible qu'on declare des extensions similaires : 
 `  $extensionsautorisees = array("jpeg", "jpg", "JPG", "JPEG");`

**Comment by jipexu** [comment]
Pourquoi? (oui il s'agit du meme format mais il faut bien prendre en compte toutes les représentations de l'extension ... non ?)
où ça?
Qu'est ce que tu proposes ?

**Comment by Jireck-npds** [comment]
non il ne faut pas prendre toutes les représentations de l'extention
sinon tu oubli :
JpG 
JPG
....
photosize.php

D'ailleurs je ne comprends pas l'utilisation de photosize.php

Soit l'Admin force le resize automatique.
Soit l'Admin laisse l'utilisateur mettre ce qu'il veux.

**Comment by jipexu** [comment]
> D'ailleurs je ne comprends pas l'utilisation de photosize.php

moi non plus

**Comment by Jireck-npds** [comment]
Parle z en a qui de droit
